application: css-fulltext
version: 1
runtime: python
api_version: 1

handlers:
- url: /cron/.*
  script: cron.py
  login: admin

- url: /worker/.*
  script: cron.py
  login: admin

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: front.py
